-
 name: This playbook will install nginx and start it. 
 hosts: servers
 become: yes
 tasks:
   - name: install nginx web server
     apt: 
       name: nginx
       state: latest
   - name: start nginx service
     service:
       name: nginx
       state: started
       enabled: yes
